### ISSUE TITLE
Suggestion: Global Client Initialization

### ISSUE THREAD

**Issue by michaelokuboyejo** [mmuoDev/okra-php-wrapper#1]
First of all, great work on putting this together. 🎉👏🏼

I thought to share my opinion and concern about the way the wrapper is designed. 

How about implementing a global initialization approach where the user/caller initializes the Client with the auth dependencies once and for all?

That way, the caller/user does not have to pass the auth token everytime and everywhere an API action needs to be taken

Here's a snippet:

```php
$client = new Client('<key>');
$client->doSomeStuff();

// Fetching Balance
$balance = $client->getBalance();
```

**Comment by mmuoDev** [comment]
Hello Michael,

Oh I get! Thank you for this! Surely gonna look into implementing this.

Regards,
Obioha Uche
Software/AI Developer
https://mmuo.dev

**Comment by mmuoDev** [comment]
This has now been implemented. Thanks @michaelokuboyejo
